extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_ground_lights;
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[414];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_ground[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
